[LWR-79] - Added Tabs component
JudicialCouncilOfCalifornia/jcc_storybook pull request #13
Opened 2023-04-05 01:56 UTC by paboden

LWR-79

Added component Tabs

2023-04-06 05:54 UTC, sleepingmonk requested changes

2023-04-06 05:54 UTC, sleepingmonk commented on src/stories/Molecules/Tabs/Tabs.js
> +    new Tabs(tablists[i]);
Make sure this is only running on each tablets once.  Use the same check and set an identifier class to see if it's been processed.  i.e. `.js-tabs`.

You should be able to do that in the loop before you instantiate the class.

2023-04-06 05:54 UTC, sleepingmonk commented on src/stories/Molecules/Tabs/Tabs.twig
> +  'stack',
You may or may not want stack here, as it does have side effects on immediate child elements due to flex.  See notes in CSS.

2023-04-06 05:54 UTC, sleepingmonk commented on src/stories/Molecules/Tabs/readme.md
> +<!-- This is the general documentation layout. Add or remove any sections as needed, but try to stay consistent across components. -->
Don't forget to update the docs!  :)

2023-04-06 20:13 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +  text-align: center;
done 👍

2023-04-06 20:13 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +  border-radius: 0;
done 👍

2023-04-06 20:13 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +
done 👍

2023-04-06 20:13 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +.tabs .tablist button:last-child {
done 👍

2023-04-06 20:13 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +.tabs .tablist button::after {
done 👍

2023-04-06 20:15 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +/* Alternate tabs styling */
Forgot to ask about this in standup. Since it's done and refined, I thinking we can leave in for now. We can remove once we know for sure it will not be apart of the official design.

2023-04-06 20:16 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +  border-right: 1px dotted var(--color-base);
done 👍

2023-04-06 20:16 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.css
> +.tabs--alternate .tablist button span {
done 👍

2023-04-06 20:17 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.js
> +    new Tabs(tablists[i]);
done 👍

2023-04-06 20:17 UTC, paboden commented on src/stories/Molecules/Tabs/Tabs.twig
> +  'stack',
done 👍

2023-04-06 20:33 UTC, paboden commented on src/stories/Molecules/Tabs/readme.md
> +<!-- This is the general documentation layout. Add or remove any sections as needed, but try to stay consistent across components. -->
Docs updated 👍

2023-04-14 05:44 UTC, paboden commented
This PR and branch can be deleted. Work is moved to this PR+branch - https://github.com/JudicialCouncilOfCalifornia/jcc_storybook/pull/19

2023-04-17 19:45 UTC, closed without merging