Review changes for News variant
JudicialCouncilOfCalifornia/jcc_storybook pull request #179
Opened 2024-01-31 01:01 UTC by archanajcc

2024-01-31 23:14 UTC, paboden requested changes
See changes

2024-01-31 23:29 UTC, archanajcc commented on src/stories/Molecules/List/List.twig
got it, thanks Phil!

2024-02-01 00:31 UTC, paboden approved these changes
Looks good. Approved.

2024-02-01 00:31 UTC, paboden approved these changes

2024-02-01 00:32 UTC, merged