action lists
JudicialCouncilOfCalifornia/jcc_storybook pull request #26
Opened 2023-04-19 19:30 UTC by baptisten

2023-04-20 20:48 UTC, sleepingmonk requested changes
A couple of small things.

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/ActionList.css
> +.action-list {}
No styles here so you can remove this line.

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/ActionList.css
> +.action-list .action-item {
Name like this:  `.action-list__item {` instead, for consistency in the codebase.
See the last bit of this section of the docs.  https://judicialcouncilofcalifornia.github.io/jcc_storybook/?path=/docs/documentation-cssbestpractices--default#bem-style-class-names

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/ActionList.css
> +.action-list .action-item:last-child {
`.action-list__item:last-child {`

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/ActionList.data.js
> +import drupalAttribute from 'drupal-attribute'
Please remove.

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/ActionList.stories.js
> +    attributes: {table: {disable: true}},
Please remove the attributes line.

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/readme.md
> +<!-- This is the general documentation layout. Add or remove any sections as needed, but try to stay consistent across components. -->
Don't forget to document the component.

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/ActionList.twig
> +        <div class="action-item cluster box">
Class should be `action-list__item` for consistency with the codebase.

2023-04-20 20:48 UTC, sleepingmonk commented on src/stories/Molecules/ActionList/ActionList.twig
> +    <div class="box">
I suspect we don't want a box here.  The padding for the whole component will be set by its parent.  However the box on the items is ok because it intentionally insets the item content inside the borders.  I'm sure this is the intention of the design even though the mockup does a poor job of keeping content lined up to edge properly.

2023-04-25 22:29 UTC, baptisten commented
It should be fixed @sleepingmonk

2023-05-02 17:33 UTC, merged