LWR-190: added media caption plus alignment fix
JudicialCouncilOfCalifornia/jcc_storybook pull request #50
Opened 2023-05-11 22:05 UTC by melwong-jcc

2023-05-11 23:50 UTC, melwong-jcc commented
Instead of just hiding caption, I am going to add attributes like ALT for accessibility needs. Feel free to start reviewing the visible caption candidate.

2023-05-16 18:09 UTC, sleepingmonk requested changes

2023-05-16 18:09 UTC, sleepingmonk commented on src/stories/Molecules/Card/Card.css
> -.card > .switcher.wrapping {
This rule can't be removed.  It fixes LWR-172

2023-05-16 18:09 UTC, sleepingmonk commented on src/stories/Molecules/Card/Card.css
> +.card__media .frame .card__media_caption {
You can probably just use `.card__media-caption` instead of this chain of classes.

And since you're using `margin-block-start` I don't think you need the "stack" class on "fame" div in the template as this rule just overrides the margin added by the stack class.

2023-05-16 18:09 UTC, sleepingmonk commented on src/stories/Molecules/Card/Card.twig
> +        <div class="frame stack">
Shouldn't need the stack with the margin on the caption class in your CSS.

2023-05-17 07:46 UTC, merged