globalbranding story
JudicialCouncilOfCalifornia/jcc_storybook pull request #6
Opened 2023-02-21 23:46 UTC by baptisten

Let me know any update needed

2023-02-23 20:40 UTC, sleepingmonk requested changes
Thanks @baptisten This is pretty good.  Just a couple of notes.

Seems like a lot of comments but they're really small touch ups and additional guidance for context.

2023-02-23 20:40 UTC, sleepingmonk commented on src/css/scheme-default.css
> +  --font-global-brand: 'Lora' ,'Georgia' ,'Cambria' ,'Times New Roman','Times' ,serif;
Should probably add Lora font to the @import at the top of the file:

https://fonts.google.com/specimen/Lora?query=lora

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.css
> +    font-family: --font-global-brand;
Should be `var(--font-global-brand)`.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.css
> +    padding: 0 var(--s0);
I'll pull this down and view the results but I'm suspicious of this padding on the `a`.  

My thought would be that any space between this text and other elements would be managed by the context that wraps them.  

For example, the Hat will be a cluster, which will include a gap between this and the secondary nav component automatically.

```
<div class="hat">
  <div class="container box"> <!-- Container for max width, box for edge padding. -->
      <div class="cluster"> <!-- Cluster manages relationship/space between child elements. -->
         <GlobalBranding> <!-- Padding on this would misalign it with the left edge of all other content. -->
         <SecondaryNav>
      </div>
   </div>
</div>
```

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.css
> +    color: var(--color-white);
Set this to: 
`color: var(--color, var(--color-white));`

This way it can inherit the color it needs from the parent element, or fall back to white.

From the hat example:
```
<div class="hat" style="--color: var(--color-white);">
```

Then this sub component, as well as the secondary nav link color can be set by the context (hat) which is what will determine its background color.  This way we can avoid having to override this low level color value if we find our selves in a sub footer or some other context that has a light background.

In other words, the lower level the element, the less assumptions it should make about its style properties.

This is how we avoid overrides and make the most out of the natural cascade of CSS.  It eliminates SOOOO much code.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.data.js
> +  another_variant: {
Delete the example variant.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.css
> +.global-branding.global-branding--inverted a{
See color comments above.  This can be removed if the context sets the color.  We don't need an "inverted" variant.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.data.js
> +    sub_component_data: {
There's no sub component, so this can be removed.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.stories.js
> +  parameters: {
You can add a Storybook parameter here just for presentational aesthetics.
`layout: "centered",`

If that does something weird, like make the text wrap, try "padded" instead.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.stories.js
> +    variant: {
No variant, so feel free to remove.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/GlobalBranding.twig
> +  <div class="global-branding__wrapper">
We probably don't need these additional __wrapper and __inner divs.  They're not used for styling anything.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/readme.md
> +Description of the Global Branding in markdown.
Update this to describe what this component is, does, or is for.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/readme.md
> +  - `--name`: description...
`--color`: Sets the font color.

2023-02-23 20:40 UTC, sleepingmonk commented on src/stories/Atoms/GlobalBranding/readme.md
> +  variant: "default",
Once you've finalized the "data.js" for this, copy the structure here for easy reference by anyone integrating this, using the docs as a guide.

2023-02-23 23:04 UTC, baptisten commented on src/css/scheme-default.css
> +  --font-global-brand: 'Lora' ,'Georgia' ,'Cambria' ,'Times New Roman','Times' ,serif;
Right! I added it to the import

2023-02-23 23:05 UTC, baptisten commented on src/stories/Atoms/GlobalBranding/GlobalBranding.css
> +    font-family: --font-global-brand;
I corrected it

2023-02-23 23:06 UTC, baptisten commented on src/stories/Atoms/GlobalBranding/GlobalBranding.css
> +    padding: 0 var(--s0);
I understand... I checked how things were done on TC.
But this comment makes sense.

2023-02-23 23:07 UTC, baptisten commented on src/stories/Atoms/GlobalBranding/GlobalBranding.css
> +    color: var(--color-white);
I corrected it.
I didn't know this syntax, so thanks for sharing the info!

2023-02-28 00:31 UTC, sleepingmonk approved these changes

2023-02-28 00:31 UTC, merged